### ISSUE TITLE
Adds `(` in certain conditions

### ISSUE THREAD

**Issue by ryanmr** [nick-lvov-dev/typescript-explicit-types#2] opened 2020-09-27 03:35 UTC
plugin version: 0.0.5
This is some code from a NestJS app codebase, pretty plain / mostly unimplemented controller.

```ts
import { Controller, Post, Body } from '@nestjs/common';
import { ConnectionsService } from './connections.service';
import { CreateConnectionDto } from './dto/create-connection.dto';

@Controller('connections')
export class ConnectionsController {
  constructor(private readonly connectionsService: ConnectionsService) {}

  @Post()
  async create(@Body() createConnectionDto: CreateConnectionDto) {
    return this.connectionsService.handle(createConnectionDto);
  }
}
```

When explicit types runs on `create`, it will add an extra `(` as the return type.

```ts
  @Post()
  async create(@Body() createConnectionDto: CreateConnectionDto)( {
    return this.connectionsService.handle(createConnectionDto);
  }
```

I tried taking the `@Annotations()` for post and controller out to see if that was the confusion, but it still repeated the same issue.

Let me know if it would be easier to help debug this with a reproduction example repo.

**Comment by ryanmr** [comment] 2020-09-27 03:49
Sorry, didn't realize a new update was available.

In version 0.0.6:

```
  @Post()
  async create: CreateConnectionDto): Promise<void>(@Body() createConnectionDto: CreateConnectionDto) {
    return this.connectionsService.handle(createConnectionDto);
  }
```

**Comment by nick-lvov-dev** [comment] 2020-09-27 03:59
Hmm, I see, will fix now

**Comment by nick-lvov-dev** [comment] 2020-09-27 05:02
@ryanmr fix is out, should be live shortly

**Comment by nick-lvov-dev** [comment] 2020-10-08 07:47
Looks like the issue is fixed, closing this

**Closed as completed by nick-lvov-dev** 2020-10-08 07:47 UTC
